---
title: "COSMO_MOON_NCI60"
author: "Aurelien dugourd"
date: "2024-06-04"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tutorial with NCI60 cohort

# libraries, data loading and feature selection

```{r libraries and data loading}
# We advise to instal from github to get the latest version of the tool.
# if (!requireNamespace("devtools", quietly = TRUE))
#   install.packages("devtools")
# 
# devtools::install_github("saezlab/cosmosR")

library(cosmosR)
library(reshape2)
library(readr)

data("meta_network")

meta_network <- meta_network_cleanup(meta_network)

load("data/cosmos/cosmos_inputs.RData")

names(cosmos_inputs)

cell_line <- "786-0"

#see scripts/prepare_cosmos_inputs.R
sig_input <- cosmos_inputs[[cell_line]]$TF_scores
metab_input <- cosmos_inputs[[cell_line]]$metabolomic
RNA_input <- cosmos_inputs[[cell_line]]$RNA
```

```{r format metabolomic input and select upstream input}
#Choose which compartment to assign to the metabolic measurments
metab_input <- prepare_metab_inputs(metab_input, c("c","m"))

##Filter significant inputs
sig_input <- sig_input[abs(sig_input) > 2]
# metab_input <- metab_input[abs(metab_input) > 2]
```

# Filter inputs and prior knowledge network

```{r Filter inputs and prior knowledge network}
#Remove genes that are not expressed from the meta_network
start.time <- Sys.time()
meta_network_old <- cosmosR:::filter_pkn_expressed_genes(names(RNA_input), meta_pkn = meta_network)
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken

start.time <- Sys.time()
meta_network <- filter_pkn_expressed_genes_2(names(RNA_input), meta_pkn = meta_network)
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken

identical(meta_network_old, meta_network)

#Filter inputs and prune the meta_network to only keep nodes that can be found downstream of the inputs
#The number of step is quite flexible, 7 steps already covers most of the network

n_steps <- 6

# in this step we prune the network to keep only the relevant part between upstream and downstream nodes
sig_input <- cosmosR:::filter_input_nodes_not_in_pkn(sig_input, meta_network)
meta_network <- cosmosR:::keep_controllable_neighbours(meta_network, n_steps, names(sig_input))
metab_input <- cosmosR:::filter_input_nodes_not_in_pkn(metab_input, meta_network)
meta_network <- cosmosR:::keep_observable_neighbours(meta_network, n_steps, names(metab_input))
sig_input <- cosmosR:::filter_input_nodes_not_in_pkn(sig_input, meta_network)


#compress the network
meta_network_compressed_list <- compress_same_children(meta_network, sig_input = sig_input, metab_input = metab_input)

meta_network_compressed <- meta_network_compressed_list$compressed_network

node_signatures <- meta_network_compressed_list$node_signatures

duplicated_parents <- meta_network_compressed_list$duplicated_signatures

meta_network_compressed <- meta_network_cleanup(meta_network_compressed)
```

# run MOON ot score the and contextualise the PKN

```{r run MOON ot score the and contextualise the PKN}
load("support/dorothea_reg.RData")

meta_network_TF_to_metab <- meta_network_compressed

before <- 1
after <- 0
i <- 1
while (before != after & i < 10) {
  before <- length(meta_network_TF_to_metab[,1])
  moon_res <- moon(upstream_input = sig_input, 
                                                 downstream_input = metab_input, 
                                                 meta_network = meta_network_TF_to_metab, 
                                                 n_layers = n_steps, 
                                                 statistic = "ulm") 
  
  meta_network_TF_to_metab <- filter_incohrent_TF_target(moon_res, dorothea_reg, meta_network_TF_to_metab, RNA_input)
  after <- length(meta_network_TF_to_metab[,1])
  i <- i + 1
}

if(i < 10)
{
  print(paste("Converged after ",paste(i-1," iterations", sep = ""),sep = ""))
} else
{
  print(paste("Interupted after ",paste(i," iterations. Convergence uncertain.", sep = ""),sep = ""))
}

#####
write_csv(moon_res, file = paste("results/moon/",paste(cell_line, "_ATT_decouplerino_full.csv",sep = ""), sep = ""))
```

```{r extract subnetwork from scored MOON network}
source("scripts/support_decompression.R")
moon_res <- decompress_moon_result(moon_res, meta_network_compressed_list, meta_network_TF_to_metab)[,c(4,2,3)]
names(moon_res)[1] <- "source"

plot(density(moon_res$score))
abline(v = 1)
abline(v = -1)

solution_network <- reduce_solution_network(decoupleRnival_res = moon_res, 
                                            meta_network = meta_network,
                                            cutoff = 0, 
                                            upstream_input = sig_input, 
                                            RNA_input = RNA_input, 
                                            n_steps = n_steps)

SIF <- solution_network$SIF
names(SIF)[3] <- "sign"
ATT <- solution_network$ATT

data("HMDB_mapper_vec")

translated_res <- translate_res(SIF,ATT,HMDB_mapper_vec)

SIF <- translated_res[[1]]
ATT <- translated_res[[2]]

write_csv(SIF, file = paste("results/",paste(cell_line, "_dec_compressed_SIF.csv",sep = ""), sep = ""))
write_csv(ATT, file = paste("results/",paste(cell_line, "_dec_compressed_ATT.csv",sep = ""), sep = ""))
```
```{r}
library(decoupleR)
library(GSEABase)

source("support/support_functions.R")

reactome <- import_gmt("support/c2.cp.reactome.v2024.1.Hs.symbols.gmt")[,c(2,1)]
names(reactome) <- c("source","target")
reactome$mor <- 1

row.names(ATT) <- ATT$Nodes

reactome_scores <- decoupleR::run_ulm(ATT[,2,drop = F], reactome, minsize = 2)
reactome_scores_df <- dcast(reactome_scores, source~condition, value.var = "score")

```

```{r}
library(ggplot2)
RNA <- as.data.frame(cosmos_inputs[[cell_line]]$RNA)
names(RNA) <- "RNA"

reactome_scores <- decoupleR::run_ulm(RNA, reactome, minsize = 2)
reactome_scores_df <- dcast(reactome_scores, source~condition, value.var = "score")

BCCA <- RNA[row.names(RNA) %in% reactome[reactome$source == "REACTOME_BRANCHED_CHAIN_AMINO_ACID_CATABOLISM","target"],,drop = F]
BCCA$gene <- row.names(BCCA)
BCCA <- BCCA[order(BCCA$RNA, decreasing = F),]
BCCA$gene <- factor(BCCA$gene, levels = BCCA$gene)

ggplot(BCCA, aes(x = gene, y = RNA)) + geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) 

```

```{r}
moon_res
first_cutoff <- 2
top_scores <- moon_res[abs(moon_res$score) > first_cutoff,]
sub_net <- meta_network[meta_network$source %in% top_scores$source | meta_network$target %in% top_scores$source,]
#this removes nodes that are not top cutoff and not intermediates between two top cutoff nodes
sub_net <- sub_net[(sub_net$source %in% sub_net$target & sub_net$target %in% sub_net$source) | (sub_net$source %in% top_scores$source & sub_net$target %in% top_scores$source),]
secondary_cutoff <- 1
secondary_scores <- moon_res[abs(moon_res$score) > secondary_cutoff,]
sub_net <- sub_net[sub_net$source %in% secondary_scores$source & sub_net$target %in% secondary_scores$source,]
names(sub_net) <- c("source","target","sign")
sub_net_ATT <- moon_res[(moon_res$source %in% sub_net$source | moon_res$source %in% sub_net$target),]

sub_net$coherence <- apply(sub_net,1,function(x,sub_net_ATT){
  sign(sub_net_ATT[sub_net_ATT$source == x[1],"score"] * sub_net_ATT[sub_net_ATT$source == x[2],"score"]) == sign(as.numeric(x[3]))
},sub_net_ATT = sub_net_ATT)

SIF <- sub_net[sub_net$coherence,]
ATT <- sub_net_ATT[(sub_net_ATT$source %in% sub_net$source | sub_net_ATT$source %in% sub_net$target),]
```

```{r session info}
sessionInfo()
```

